Change ETS plots max and min values
SPiN-Lab/connPFM pull request #25
Opened 2021-11-05 15:26 UTC by vinferrer

Closes # .

Changes proposed in this pull request:

-
-

2021-11-05 15:27 UTC, vinferrer commented
![image](https://user-images.githubusercontent.com/38909338/140535851-3529c7df-98b0-4ba5-bc31-23385c887f1e.png)

Left is ets_AUC, right is ets_original, both thresholded in the RSS selected points

2021-11-05 15:29 UTC, vinferrer commented
![image](https://user-images.githubusercontent.com/38909338/140536058-74a41af4-3643-4f28-a7b3-6c3f6903b0e4.png)
Left it's ets_AUC, Right ets_original, both with the thresholding for selected RSS

2021-12-09 09:22 UTC, vinferrer commented
![ets_AUC_denoisedrss](https://user-images.githubusercontent.com/38909338/145369044-75b24be6-caf7-40c7-a803-cefa90a0cf76.png)

2021-12-09 11:38 UTC, eurunuela requested changes
The changes look good to me. Just have one comment.

2021-12-09 11:38 UTC, eurunuela commented on connPFM/tests/test_ev.py
> +    )
Could you please check that the file is being generated.

2021-12-09 11:50 UTC, vinferrer commented
All done @eurunuela

2021-12-09 11:59 UTC, eurunuela approved these changes
LGTM! Thanks @vinferrer !

2021-12-09 12:50 UTC, merged