stop creating the nilearn_cache folder
SPiN-Lab/connPFM pull request #29
Opened 2021-11-09 11:09 UTC by vinferrer

Changes proposed in this pull request:

- Now the memory option in the masker is not used
-

2021-11-12 10:55 UTC, eurunuela requested changes
LGTM @vinferrer . I would remove the memory argument though, as the default is cache. I think it would make it easier to read.

2021-11-12 10:55 UTC, eurunuela commented on connPFM/connectivity/ev.py
> +        memory="",
```suggestion
```

2021-11-12 10:55 UTC, eurunuela commented on connPFM/debiasing/debiasing.py
> +        memory="",
```suggestion
```

2021-11-12 10:55 UTC, eurunuela commented on connPFM/connectivity/ev.py
> +        memory="",
The default is no cache.

2021-11-12 10:55 UTC, eurunuela commented on connPFM/deconvolution/roiPFM.py
> +    masker = NiftiLabelsMasker(labels_img=atlas, standardize="psc", memory="", strategy="mean")
```suggestion
    masker = NiftiLabelsMasker(labels_img=atlas, standardize="psc", strategy="mean")
```

2021-11-12 10:55 UTC, eurunuela commented on connPFM/tests/test_ev.py
> +        memory="",
```suggestion
```

2021-11-12 10:55 UTC, eurunuela commented on connPFM/tests/test_ev.py
> +        memory="",
```suggestion
```

2021-11-12 10:55 UTC, eurunuela commented on connPFM/utils/surrogate_generator.py
> +        labels_img=atlas, standardize="psc", memory="", strategy="mean"
```suggestion
        labels_img=atlas, standardize="psc", strategy="mean"
```

2021-11-12 10:55 UTC, eurunuela commented on ismrm2022/stability_pfm.py
> +        memory="",
```suggestion
```

2021-11-15 10:48 UTC, vinferrer commented
is done

2021-11-15 14:15 UTC, eurunuela approved these changes
LGTM, thank you @vinferrer !

2021-11-15 18:03 UTC, merged